FROM node:20-alpine AS base
WORKDIR /app
RUN apk add --no-cache libc6-compat openssl

COPY package*.json ./
COPY packages/config/package*.json ./packages/config/
COPY packages/email/package*.json ./packages/email/
COPY packages/database/package*.json ./packages/database/
COPY apps/worker/package*.json ./apps/worker/

RUN npm install

COPY . .

# In production container, use PostgreSQL schema
RUN cp packages/database/prisma/schema.postgresql.prisma packages/database/prisma/schema.prisma

RUN npm --workspace=@vxmail/database run generate

CMD ["npm", "--workspace=@vxmail/worker", "run", "start"]
